<div class="item">
	<div class="item-inner font2">
		<div class="item-box">
			<?php 
			$_product = Mage::getModel('catalog/product')->load($item['id']);
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			$isBestProduct =($_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';                				
			
			if ($now>=$newsFrom && $now<=$newsTo){
				echo "<span class='newproduct-grid'>new</span>";
				//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
			}
			if ($specialprice){
				echo "<span class='saleoff-grid'>sale off</span>";
			}
			if ($isBestProduct){
				echo "<span class='bestproduct-grid'>best</span>";
			}			
			?>	
			<div class="product-image">
				<a style="display:<?php echo ($config['product_image_disp'])?"block":"none";?>" class="" href="<?php if($config['product_image_linkable'] == 1){ echo $_product->getProductUrl() ;} else{ echo "#";}?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img  style="display:<?php echo ($config['product_image_disp'])?"block":"none";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,215); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<div class="item-box-hover ">
					<?php if($_product->isSaleable()): ?>
						<a title="<?php echo $this->__('Add to Cart') ?>" href="<?php  echo $this->getAddToCartUrl($_product) ?>" class="btn-cart fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a>
					<?php else: ?>
						<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
					<?php endif; ?>	
					<a style="<?php echo ($config['product_details_page_link_disp'])?"":"display:none";?>;" class="readmore fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><?php echo $this->__('More Detail')  ?></a>									
				</div>	
			</div>	
		</div>	
		<div class="item-box-footer">
			<h2 class="product-name" style="display:<?php echo ($config['product_title_disp'])?"block":"none";?>;">	
				<a class="fontcolor" href="<?php if($config['product_image_linkable'] == 1){ echo $_product->getProductUrl() ;} else{ echo "#";}?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
				<?php 
				if(strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 15){
					echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 15) .' ...';
				}else{
					echo $_helper->productAttribute($_product, $_product->getName(), 'name');
				}
				?>
				</a>
			</h2>	
			<div class="so_content" style="display:<?php echo ($config['product_description_disp'])?"display":"none";?>;">	       			
				<div class="so_description"><?php echo $item['sub_content'];?></div>
			</div>		
			<?php if($config['product_price_disp'] == 1){										
					echo $this->getPriceHtml($_product, true);									
			} ?>
		</div>		

	</div>
</div>