<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>


<div class="content-area">
    <div class="product-detail-container">
        <div class="product-detail">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>
                <div class="product-img-container">
                    <div class="product-img">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(160, 176) ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>" />
                    </div>
                </div>

                <div class="product-info">
                    <div>
                        <span class="label">Brand:</span>
                        <span class="info"><?php echo $_product->getAttributeText('manufacturer') ?></span>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <span class="label">Product Name:</span>
                        <span class="info"><?php echo $_product->getName() ?></span>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <span class="label">Weight:</span>
                        <span class="info"><?php echo $_product->getWeight() ?></span>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <span class="label">Description:</span>
                        <span class="info">
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </span>
                        <div class="clear"></div>
                    </div>
                    <!--                
                                    <div>
                                        <span class="label">Offer:</span>
                                        <span class="info">Buy 2 Get 1 FREE</span>
                                        <div class="clear"></div>
                                    </div>
                    -->
                    <div>
                        <?php echo $this->getTierPriceHtml() ?>
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getChildHtml('extrahint') ?>

                        <div class="clear"></div>
                    </div>
                    <!--
                                    <div>
                                        <span class="label">Quantity:</span>
                                        <span class="info">
                                            <input type="text" value="1" class="quantity" />
                                        </span>
                                        <div class="clear"></div>
                                    </div>
                    -->

                    <?php if (!$this->hasOptions()): ?>
                        <div class="add-to-box">
                            <?php if ($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                        </div>
                    <?php elseif (!$_product->isSaleable()): ?>
                        <div class="add-to-box">
                            <?php echo $this->getChildHtml('addto') ?>
                        </div>
                    <?php endif; ?>


                    <!--<a class="button btnAddToCart" href="#">Add to Cart</a>-->
                </div>
            </form>
            <div class="clear"></div>
        </div>
    </div>


    <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url) {
            if (this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
        //]]>
    </script>


    <div class="product-container">
        <fieldset class="related-products">
            <legend>Related Products</legend>
            <div class="product-collateral">
                <?php echo $this->getChildHtml('upsell_products') ?>
                <?php echo $this->getChildHtml('product_additional_data') ?>
            </div>
        </fieldset>
    </div>
</div>
