<footer>
    <div class="footer-content">
        <div class="center">
            <!-- FOOTER CONTENT -->
            <div class="footer-links-container">
                <div class="footer-links">
                    <span class="link-group-title">Information</span>
                    <ul>
                        <li><a href="#" class="info">About Us</a></li>
                        <li><a href="#" class="van">Delivery Information</a></li>
                        <li><a href="#" class="lock">Privacy Policy</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <span class="link-group-title">Customer Service</span>
                    <ul>
                        <li><a href="#" class="contact">Contact Us</a></li>
                        <li><a href="#" class="van">Returns</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <span class="link-group-title">My Account</span>
                    <ul>
                        <li><a href="#" class="myaccount">My Account</a></li>
                        <li><a href="#" class="order">Order History</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml() ?>
</footer>

<script src="<?php echo $this->helper('core/js')->getJsUrl('webonik/plugins/jquery.mCustomScrollbar.min.js') ?>"></script>
<script src="<?php echo $this->helper('core/js')->getJsUrl('webonik/plugins/jquery.cycle2.min.js') ?>"></script>
<script src="<?php echo $this->helper('core/js')->getJsUrl('webonik/plugins/plugins.js') ?>"></script>
<script src="<?php echo $this->helper('core/js')->getJsUrl('webonik/script.js') ?>"></script>
