<header>
    <nav>
        <div class="center">
            <ul>
                <li><a href="<?php echo $this->getUrl('') ?>" class="home"><span></span>Home</a></li>
                <li><a href="<?php echo $this->getUrl('customer/account')?>" class="account"><span></span>My Account</a></li>
                <li><a href="<?php echo $this->getUrl('checkout/cart')?>" class="cart"><span></span>Shopping Cart</a></li>
                <li><a href="<?php echo $this->helper('checkout/url')->getCheckoutUrl(); ?>" class="checkout"><span></span>Checkout</a></li>
            </ul>
            
            <ul class="pc-inline float-right">
                <li class="search-container">
                    <?php echo $this->getChildHtml('topSearch') ?>
                </li>
                <?php 
                if($this->helper('customer')->isLoggedIn()){
                ?>
                <li><a href="<?php echo $this->helper('customer')->getLogoutUrl() ?>" class="logout">Logout</a></li>
                <?php }else{ ?>
                <li><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="login"><span></span>Log In</a></li>
                <li><a href="<?php echo $this->helper('customer')->getRegisterUrl() ?>" class="register">Register</a></li>
                <?php } ?>
            </ul>
            <ul class="mobile-inline float-right">
                <li><a href="#" class="login"><span></span>Log In</a></li>
                <li><a href="#" class="register">Register</a></li>
            </ul>
        </div>
    </nav>
    <div class="header-content">
        <div class="center">
            <a href="<?php echo $this->getUrl('') ?>" class="logo"></a>
            <form class="search-form mobile-inline float-right">
                <input type="text" placeholder="Search product here..." />
                <button type="submit" class="btnSearch">Search</button>
            </form>
            <div class="clear mobile"></div>
            <div class="pc-inline">
                <a href="tel:01952027655" class="tel">0195 2027 655</a>
                <span class="address">Baily Road, Shiddeshwari and Shantinagar</span>
            </div>
            <div class="mobile toggle-nav-container">
                <a href="javascript:void(0);" class="side-nav"><span></span></a>

                <a href="tel:01952027655" class="tel">Phone</a>
                <a href="javascript:void(0);" class="address deliveryLocations">Locations</a>

                <a href="javascript:void(0);" class="quick-cart"><span></span></a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</header>