<header>
    <nav>
        <div class="center">
            <ul>
                <li><a href="index.html" class="home"><span></span>Home</a></li>
                <li><a href="#" class="account"><span></span>My Account</a></li>
                <li><a href="#" class="cart"><span></span>Shopping Cart</a></li>
                <li><a href="#" class="checkout"><span></span>Checkout</a></li>
            </ul>
            <ul class="pc-inline float-right">
                <li class="search-container">
                    <form class="search-form">
                        <input type="text" placeholder="Search product here..." />
                        <button type="submit" class="btnSearch">Search</button>
                    </form>
                </li>
                <li><a href="#" class="login"><span></span>Log In</a></li>
                <li><a href="#" class="register">Register</a></li>
            </ul>
            <ul class="mobile-inline float-right">
                <li><a href="#" class="login"><span></span>Log In</a></li>
                <li><a href="#" class="register">Register</a></li>
            </ul>
        </div>
    </nav>
    <div class="header-content">
        <div class="center">
            <a href="index.html" class="logo"></a>
            <form class="search-form mobile-inline float-right">
                <input type="text" placeholder="Search product here..." />
                <button type="submit" class="btnSearch">Search</button>
            </form>
            <div class="clear mobile"></div>
            <div class="pc-inline">
                <a href="tel:01952027655" class="tel">0195 2027 655</a>
                <span class="address">Baily Road, Shiddeshwari and Shantinagar</span>
            </div>
            <div class="mobile toggle-nav-container">
                <a href="javascript:void(0);" class="side-nav"><span></span></a>

                <a href="tel:01952027655" class="tel">Phone</a>
                <a href="javascript:void(0);" class="address deliveryLocations">Locations</a>

                <a href="javascript:void(0);" class="quick-cart"><span></span></a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</header>