<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="block block-newproduct">
	<?php if ($this->title): ?>
	<?php 
		$arr_word =  $this->title ? explode(' ',$this->title) : "";
		$join_word = array_shift($arr_word).' <span>'.implode(' ',$arr_word).'</span>';
	 ?>	
	
	<?php endif; ?>
    <div class="block-content">
    	<?php if(!$_productCollection->count()): ?>
        	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: 
		$row = 0;
        $col= 0;
        $count = 1;
		foreach($_productCollection as $_product):
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			$isBestProduct =($_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';                	
            if( ($count==1) || (($count-1)%$this->getNumColumns()== 0) ){
                $row++;
            ?>
            <ul class="products list cols-<?php echo $this->getNumColumns().' row-'.$row ; ?>">
            <?php
            }?>
                <li class="item <?php echo ( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) )?"last":""; ?>">
                    <div class="item-inner">
                    	<div class="item-box">
							<?php		
										if($newsFrom != ''){							
										if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){ 
											?>
	                                        <div class='new-item'></div>
										<?php }
										}else{
										if(($newsTo != "") && $newsTo >= $now){	
										?>
											<div class='new-item'></div>
										<?php }
							}?>
							<?php
                           
                            if ($specialprice){
										 ?>
										<div class='sale-item'><span><?php			
											$saleof= abs(($specialprice/($_product->getPrice()))*100-100);
											print_r(floor($saleof));
										?></span></div>
                                    <?php }
							if ($isBestProduct){
								echo "<span class='bestproduct-grid'>best</span>";
							}								
                            ?>
                            <?php if ($this->product_image_disp): ?>
                            <div class="product-image">
                            	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            	<?php if($this->product_addtowishlist OR $this->product_addtocompare){ ?>
                            
                            <div class="actions">
                                <ul class="add-to-links">
                                	<?php if ($this->product_cart_or_status): ?>
		                            <?php if($_product->isSaleable()): ?>
		                            	<li class="addtocart">
		                                <a data-toggle="tooltip" title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></a></li>
		                            <?php else: ?>
		                                <li class="addtocart"><span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span></li>
		                            <?php endif; ?>
		                            <?php endif; ?>
                                    <?php if ($this->helper('wishlist')->isAllow() AND $this->product_addtowishlist) : ?>
                                        <li class="wishlist">
                                        	<a data-toggle="tooltip" title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
										<?php if($this->product_addtocompare){ ?>
                                        <li  class="compare"><a data-toggle="tooltip" title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php } ?>
									<?php endif; ?>
                                </ul>
                            </div>
							<?php }  ?>

                            </div>
                            <?php endif; ?>
							<div class="product-box">
							<?php if ($this->product_title_disp): ?>
								<div class="product-name">
									<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
									<?php
										if ( $this->product_title_max_length > 0){
											$_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
										}
									?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
								</div>
								<?php endif; ?>
								<?php if ($this->product_description_disp): ?>
									<div class="item-description">
										<?php
											$product_description_src = in_array($this->product_description_src, array('short_description', 'description')) ? $this->product_description_src : 'short_description';
											$product_description = $_helper->productAttribute($_product, $_product->$product_description_src, $product_description_src);
											
											if ( $this->product_description_strip_tags ){
												$allow_tags = $this->product_description_keep_tags ? $this->product_description_keep_tags : null;
												$product_description = $this->stripTags( $product_description,  $allow_tags, true);
											}
											
											if ( $this->product_description_max_length > 0){
												$product_description = Mage::helper('core/string')->truncate($product_description, (int)$this->product_description_max_length);
											}
											
											echo $product_description;
										?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
									</div>
							<?php endif; ?>		
                            
                            <?php if ($this->product_price_disp): ?>
                                <?php echo $this->getPriceHtml($_product, false, rand().time()); ?>
                            <?php endif; ?>    
                            <div class="ratings-wrap-left">
							<?php
							if( $this->product_rating_summary){								
									echo $this->getReviewsSummaryHtml($_product, false, true);
							} 
							?>		 
                            </div> 
							
							</div>
                        </div>
   
                	</div>
                </li>
            <?php
			//echo $count.' '.$_productCollection->count().' '.$this->getNumColumns();
			if( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) ){
				?>
				</ul>
				<?php
			}
			$count = $count+1;
			?>
        <?php endforeach; ?>
    <?php endif; ?>
	</div>
</div>
