<?php
$catalogSearchHelper = $this->helper('catalogsearch');
?>
<!--
<form class="search-form">
    <input type="text" placeholder="Search product here..." />
    <button type="submit" class="btnSearch">Search</button>
</form>-->

<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-search">
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength(); ?>" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="btnSearch"><?php echo $this->__('Search') ?></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
            //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
            //]]>
        </script>
    </div>
</form>
